### ISSUE TITLE
valibot validator typescript error

### ISSUE THREAD

**Issue by xxxhussein** [honojs/middleware#203]
```
Argument of type 'ObjectSchema<{ username: StringSchema<string>; password: StringSchema<string>; }, { username: string; password: string; }>' is not assignable to parameter of type 'BaseSchema<any, any>'.
  The types returned by '_parse(...)' are incompatible between these types.
    Type '_ParseResult<{ username: string; password: string; }>' is not assignable to type '_ParseResult<any>'.
      Type '{ output?: undefined; issues: Issues; }' is not assignable to type '_ParseResult<any>'.ts(2345)
```

```ts
const loginSchema = object({
  username: string("Username must be a string", [
    minLength(1, "Username is too short"),
  ]),
  password: string("Password must be a string", [
    minLength(1, "Password is too short"),
  ]),
});

app.post("/login", vValidator("json", loginSchema), async (c) => {
  const { username, password } = c.req.valid("json");
  const [user] = await db
    .select()
    .from(users)
    .where(eq(users.username, username));
  if (!user) return c.text("No user", 400);

  return c.json(user);
});```

**Comment by yusukebe** [comment]
Hi @xxxhussein,

Sorry for the late reply. I can't reproduce the issue. Could you please provide minimal snippets or a project to reproduce the problem?

**Comment by sinh117801** [comment]
Hello @yusukebe I have a similar issue with zod-validator, maybe it could help.
 + @hono/zod-validator@0.1.10
 + hono@3.9.0
 + zod@3.22.4
 + bun@1.0.7
[template-test.zip](https://github.com/honojs/middleware/files/13196111/template-test.zip)


error I get:

```
Type instantiation is excessively deep and possibly infinite.ts(2589)
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'MiddlewareHandler<Env, string, { in: any; out: { json: { ping: string; }; }; }>' is not assignable to parameter of type 'H<Env, "/", {}, HandlerResponse<any>>'.
      Type 'MiddlewareHandler<Env, string, { in: any; out: { json: { ping: string; }; }; }>' is not assignable to type 'MiddlewareHandler<Env, "/", {}>'.
        Types of parameters 'c' and 'c' are incompatible.
          Type 'Context<Env, "/", {}>' is not assignable to type 'Context<Env, string, { in: any; out: { json: { ping: string; }; }; }>'.
            Types of property 'req' are incompatible.
              Property 'paramData' is missing in type 'HonoRequest<"/", unknown>' but required in type 'HonoRequest<string, { json: { ping: string; }; }>'.ts(2769)
```

![image](https://github.com/honojs/middleware/assets/43696715/9f02422e-8be3-48c1-9f90-a08a4e03849b)

**Comment by yusukebe** [comment]
Hi @sinh117801,

The issue with zod-validator is caused by a version mismatch between `@hono/zod-validator` and `hono`.

I've released a new version of `@hono/zod-validator`. Please run the following command and restart your editor:

``` 
bun add hono @hono/zod-validator
```

**Comment by iamyuu** [comment]
Hi @yusukebe, I have similar issues, you can find the repo to reproduce [here](https://github.com/iamyuu/repro-hono-valibot)

![Okb79H63 2024-03-02 at 09 22 AM@2x](https://github.com/honojs/middleware/assets/45778229/d2b8ebd3-0c2e-4352-bd27-6f55d1090c92)

note: the functionality works fine

**Comment by yusukebe** [comment]
Hi @iamyuu 

Can't reproduce it with your repro. How about remove `node_modules` and re-run `bun install`?

<img width="847" alt="Screenshot 2024-03-03 at 0 33 43" src="https://github.com/honojs/middleware/assets/10682/c9350e17-a4b3-4b2d-9e31-b8091906a088">

**Comment by iamyuu** [comment]
hmm, I'm still get it

<details>
<summary>re-clone repo & install deps</summary>

![uGVw4dvO 2024-03-03 at 10 16 PM@2x](https://github.com/honojs/middleware/assets/45778229/8d44abcc-e3b9-47b8-b8ee-eca8a059749c)

</details>

<details>
<summary>error on vs code</summary>

![ktIE4jl8 2024-03-03 at 10 16 PM@2x](https://github.com/honojs/middleware/assets/45778229/c348badf-174f-4eec-b4c6-20fb08334db9)

</details>

Wait, I'm trying importing the repo to [stackblitz](https://stackblitz.com/github/iamyuu/repro-hono-valibot?file=src/index.ts) and the error is gone. The difference is in local using `bun instll` and in stackblitz using `npm install --legacy-peer-deps` (after fail trying to use `npm install`), so what is wrong?


<details>
<summary>in local machine after using <code>npm install --legacy-peer-deps</code></summary>

![FiLjoR4z 2024-03-03 at 10 31 PM@2x](https://github.com/honojs/middleware/assets/45778229/7f21f67b-3b69-4036-a5de-115bb995fa4a)


</details>

**Comment by yusukebe** [comment]
> Wait, I'm trying importing the repo to [stackblitz](https://stackblitz.com/github/iamyuu/repro-hono-valibot?file=src/index.ts) and the error is gone. The difference is in local using `bun instll` and in stackblitz using `npm install --legacy-peer-deps` (after fail trying to use `npm install`), so what is wrong?

I don't know, but I think this is not Hono's matter. Perhaps `bun` is caching something.
